### ISSUE TITLE
Sorting problem

### ISSUE THREAD

**Issue by 5ulo** [alexis-magina/cmb2-field-post-search-ajax#11]
Inside javascript there's this block
```
if($(this).attr('data-sortable') === 1){ 
	$('#'+fid+'_results').sortable({
		handle				 : '.hndl', 
		placeholder			 : 'ui-state-highlight', 
		forcePlaceholderSize : true 
	});
}
```
This is not working for me - this strict comparsion is returning false and therefore the sorting isn't working. But if the condition is
```if($(this).attr('data-sortable') == 1){```
or
```if($(this).attr('data-sortable') === '1'){```
then it is working as expected.

Truth is that ```console.log($(this).attr('data-sortable'));``` returns `1` without quotes so it should work with strict comparsion. Why is that?

**Comment by alexis-magina** [comment]
Yes, in fact jQuery attr always returns string so strict comparison with number not work here, I updated in 1.1.3.
Thank you for report this !
