### ISSUE TITLE
Conflict with jquery-ui autocomplete (eg. tags)

### ISSUE THREAD

**Issue by 5ulo** [alexis-magina/cmb2-field-post-search-ajax#12]
This custom field is using [https://github.com/devbridge/jQuery-Autocomplete](url) which is in conflict with jquery-ui available in WordPress. The documentation says we can use `devbridgeAutocomplete()` instead of `autocomplete` in order to prevent conflict. But the conflict is still preset.

If `jquery.autocomplete.min.js` is enqueued after `jquery-ui-core` it will work on cmb field, BUT the native wordpress tags (term autocomplete) in sidebar won't. There's an error in the console saying
```Uncaught SyntaxError: Unexpected token < in JSON at position 0```

Any workaround?

**Comment by 5ulo** [comment]
Heh.. got it working ! In `jqury.autocomplete.min.js` almost at the end find
```a.fn.autocomplete=a.fn.devbridgeAutocomplete=function(c,d){```
and replace with
```a.fn.autocompleteX=a.fn.devbridgeAutocomplete=function(c,d){```
I know this is not nice solution but works without any conflict.

**Comment by alexis-magina** [comment]
Thank you for your report, I don't use often tags in my WP websites so I didn't seen that.
I tried with your suggestion and yes it works : I merged it in 1.1.3.

**Comment by 5ulo** [comment]
check also my fork.. I made it to work with terms too
