### ISSUE TITLE
Undefined index if the field is empty

### ISSUE THREAD

**Issue by mralessio** [alexis-magina/cmb2-field-post-search-ajax#17]
In case of the empty field when updating the post I'm getting the message E_NOTICE  Undefined index: authors_collection_results. 
Solved it by adding` ! empty` on the line 107 like:
`if ( ! empty( $field_args['render_row_cb'][0]->data_to_save[ $fid . '_results' ] ) ) { ... `

**Comment by alexis-magina** [comment]
Thanks for reporting this issue.
I've edited the file. (1.1.5)
