### ISSUE TITLE
Improved Composer support by publishing at Packagist.org

### ISSUE THREAD

**Issue by sebask** [alexis-magina/cmb2-field-post-search-ajax#6]
Adding the project to https://packagist.org would improve Composer support since Composer will use the Packagist to find this package.

You only need to submit and publish cmb2-field-post-search-ajax at Packagist. :)

**Comment by alexis-magina** [comment]
I added the package on packagist, but it seems I must install with 
`composer require "alexis-magina/cmb2-field-post-search-ajax":dev-master`

If I try without ":dev-master", composer throw an error : 

> Could not find package alexis-magina/cmb2-field-post-search-ajax at any version for your minimum-stability (stable)

I'm not very familiar with composer ; Anyone know how to fix this ?

**Comment by sebask** [comment]
My guess is you have to provide an actual version number instead of `dev-master`. The branch `dev-master` can be used when using Composer with a git repo. 

But it's now possible to use `alexis-magina/cmb2-field-post-search-ajax` in combination with a version number since it's published at Packagist.

**Comment by alexis-magina** [comment]
Ok, thank you for your help !
I think I undestand how its work : I created a new release for 1.1.3 in Github and Packagist see it now as a production version.

**Comment by sebask** [comment]
Yes indeed. I just tested and it works great!

Thanks for publishing the project! 😄
